### ISSUE TITLE
Feature 1 : User can create new meeting event

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create new meeting event

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to name a meeting event and add a description

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 1 04 33 PM](https://user-images.githubusercontent.com/91447324/171053912-23e4ea16-b4dc-4836-be8f-d805dd82300b.png)

![Screen Shot 2022-05-30 at 1 05 19 PM](https://user-images.githubusercontent.com/91447324/171054041-83191a9b-64bf-42db-a808-9bdbf484ca04.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

N/A

### ⚡ Client

- [x] Set up files and directories
- [x] create app file
- [x] Create header component
- [x] Create input meeting name component
- [x] create add details component
- [x] style ^^^
- [x] make components translate to web view
- [x] create select drop down 
- [x] create div spans of week days
- [x] import time select components for start time to end time
- [x] make create meeting component button
- [x] make components translate to web view

### 🧑‍⚕️ Clean Up

- [x] remove console logs
