### ISSUE TITLE
Feature 2 : User can select days of the week

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select days of the week

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to select days based on the week

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 1 10 34 PM](https://user-images.githubusercontent.com/91447324/171054444-1922a180-673a-44d9-a752-d7af2aa73b7a.png)

![Screen Shot 2022-05-30 at 1 10 46 PM](https://user-images.githubusercontent.com/91447324/171054462-399ec6f5-f36f-4cb7-8650-af29ee37c670.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

N/A

### ☁️ Server

N/A

### ⚡ Client

- [x] Add event listener for span blocks
- [x] make event handler function in component func
- [x] ^^ change state
- [x] log to console results
- [x] toggle color through class name when clicked
- [x] add hover styling and active stylings

### 🧑‍⚕️ Clean Up

- [x] clean up console logs
