### ISSUE TITLE
Feature 3 : User can select days of the month

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select days of the month

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

a user can select click to select or click and drag to select rows

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 1 13 18 PM](https://user-images.githubusercontent.com/91447324/171054624-6059d0bb-449e-4d95-b88c-64c2b211ecad.png)

![Screen Shot 2022-05-30 at 1 13 30 PM](https://user-images.githubusercontent.com/91447324/171054650-24e6a346-8c74-4b1b-b88f-cac7ecd5fa2a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

N/A

### ☁️ Server

N/A

### ⚡ Client

- [x] create event listener for changing select options
- [x] create calendar component
- [x] ^ make flex box 5 x 7 
- [x] ^ styling
- [x] ^ add values
- [x] ^ show current date 
- [x] ^ allow scroll
- [x] make calendar on web view
- [x] make view from weekdays to calendar on select change
- [x] add click to toggle functionality 
- [x] add select to rows functionality

### 🧑‍⚕️ Clean Up

- [x] remove console logs
- [x] remove unused variables
