### ISSUE TITLE
Feature 5 : User can register as a member of the meeting

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can register as a member of the meeting created

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user can register with a username to be a memeber of the meeting

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 1 16 07 PM](https://user-images.githubusercontent.com/91447324/171054931-fc37ba91-74ac-464e-b299-a8f970dde5c7.png)

![Screen Shot 2022-05-30 at 1 16 19 PM](https://user-images.githubusercontent.com/91447324/171054960-869f5bd2-9697-4a53-9dc8-96d746184a81.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] make data base schema
- [x] turn on data base
- [x] turn on pgweb

### ☁️ Server

- [x] create io connection when event is created
- [x] generate meeting id 

### ⚡ Client

- [x] add event listener to create meeting button
- [x] create a new page showing login form
- [x] create login component form
- [x] create time table component made from pulling data
- [x] link hash links to #meeting 

### 🧑‍⚕️ Clean Up

- [x] remove console logs
- [x] clean up code
