### ISSUE TITLE
Feature 6 : User can select times for the day

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select times for the day 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can select time boxes with click or click and drag to select multiple blocks

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 1 18 08 PM](https://user-images.githubusercontent.com/91447324/171055135-37a84f36-eb91-4071-8088-ba9c8bf1b376.png)

![Screen Shot 2022-05-30 at 1 18 30 PM](https://user-images.githubusercontent.com/91447324/171055158-abba6086-c263-4ea3-a7fc-b7c8005823c8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] make sure data is stored in JSON

### ☁️ Server

- [x] set up post request in whatever blocks get updated by user to users table as JSON

### ⚡ Client

- [x] make event handlers for each div elem generated for user blocks
- [x] store values and time in array
- [x] figure out data model to store in JSON
- [x] make toggle functionality
- [x] make it so on click hold it is still selecting and deselecting
- [x] when clicked on not selected, everything else will select and vise versa
- [x] user can select squares starting from initial click

### 🧑‍⚕️ Clean Up

- [x] clear out console.logs 
- [x] clear out comments
