### ISSUE TITLE
Feature 7 : User can view all members selected times

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all members selected times

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view members selected times with changing colors of green opacity

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 1 26 04 PM](https://user-images.githubusercontent.com/91447324/171055767-756cfced-1555-43af-af74-ac6dbfd7f93f.png)

![Screen Shot 2022-05-30 at 1 26 15 PM](https://user-images.githubusercontent.com/91447324/171055783-293b2bd0-d2a5-4abf-ad70-fc749b14cd0f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] 

### ☁️ Server

- [x] send user input data to an algorithm that translates its count to the group table
- [x] make sure user input data is being sent back to itself on reload --> might be done on sign in later
- [x] send the group table data to data base

### ⚡ Client

- [x] update each block to specific color depending on max inputs on the screen
- [x] change opacity of green

### 🧑‍⚕️ Clean Up

- [x] clear out console logs
- [x] clear out comments
